#!/usr/bin/env python3
"""
Generate gold standard PMID/DOI files from included_studies.json.

This script reads the included_studies.json file (generated by extract_included_studies.py)
and creates two gold standard CSV files:

1. gold_pmids_{study}.csv - PMID-only format (Wave 1, backward compatible)
   - Single column: pmid
   - Used by current evaluation workflow
   
2. gold_pmids_{study}_detailed.csv - Enhanced format (Wave 2, future-proof)
   - Columns: pmid, first_author, year, title, journal, doi
   - Enables DOI-aware evaluation (Phase 6)
   - Contains metadata for validation and debugging

The script also generates a statistics report showing:
- Total included studies
- Coverage metrics (with PMID, with DOI, with both, with neither)
- Confidence distribution
- Lookup source breakdown
- Warnings for low coverage or quality issues

Usage:
    python scripts/generate_gold_standard.py <study_name> [options]

Examples:
    # Generate both formats with default confidence threshold (0.85)
    python scripts/generate_gold_standard.py ai_2022
    
    # Use higher confidence threshold for more stringent filtering
    python scripts/generate_gold_standard.py Godos_2024 --min-confidence 0.90
    
    # Generate only the simple format (PMID-only)
    python scripts/generate_gold_standard.py sleep_apnea --simple-only
    
    # Specify custom input/output paths
    python scripts/generate_gold_standard.py ai_2022 \
        --input studies/ai_2022/included_studies.json \
        --output studies/ai_2022/gold_pmids_ai_2022.csv

Notes:
    - Requires extract_included_studies.py to have been run first
    - Only includes studies with confidence >= threshold
    - PMIDs are deduplicated (if multiple references cite same article)
    - Warns if coverage is <70% (may indicate extraction/lookup issues)
    - Compatible with existing llm_sr_select_and_score.py workflow
"""

import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Set, Optional, Tuple

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))


def load_included_studies(json_path: Path) -> Dict:
    """Load included_studies.json file."""
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data
    except FileNotFoundError:
        print(f"❌ Error: File not found: {json_path}")
        print(f"   Please run extract_included_studies.py first.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON in {json_path}: {e}")
        sys.exit(1)


def filter_by_confidence(studies: List[Dict], min_confidence: float) -> Tuple[List[Dict], List[Dict]]:
    """
    Filter studies by confidence threshold.
    
    Returns:
        Tuple of (accepted_studies, rejected_studies)
    """
    accepted = []
    rejected = []
    
    for study in studies:
        # Check if lookup_metadata exists and has confidence
        metadata = study.get('lookup_metadata', {})
        confidence = metadata.get('confidence')
        
        if confidence is None:
            # No confidence score means it was extracted from the paper but not looked up
            # We accept these as they come directly from the paper
            accepted.append(study)
        elif confidence >= min_confidence:
            accepted.append(study)
        else:
            rejected.append(study)
    
    return accepted, rejected


def extract_pmids(studies: List[Dict], deduplicate: bool = True) -> List[str]:
    """
    Extract PMIDs from studies.
    
    Args:
        studies: List of study dictionaries
        deduplicate: If True, remove duplicate PMIDs
    
    Returns:
        List of PMIDs (strings)
    """
    pmids = []
    
    for study in studies:
        pmid = study.get('pmid')
        if pmid:
            pmids.append(str(pmid))
    
    if deduplicate:
        # Check for duplicates
        pmid_counts = Counter(pmids)
        duplicates = {pmid: count for pmid, count in pmid_counts.items() if count > 1}
        if duplicates:
            print(f"\n⚠️  Found {len(duplicates)} duplicate PMID(s):")
            for pmid, count in duplicates.items():
                print(f"   PMID {pmid} appears {count} times")
            print(f"   (This is normal if multiple references cite the same article)")
        
        # Return unique PMIDs, preserving order of first occurrence
        seen = set()
        unique_pmids = []
        for pmid in pmids:
            if pmid not in seen:
                seen.add(pmid)
                unique_pmids.append(pmid)
        return unique_pmids
    
    return pmids


def generate_simple_format(pmids: List[str], output_path: Path) -> None:
    """
    Generate PMID-only CSV file (Wave 1 format).
    
    Format:
        pmid
        12345678
        23456789
        ...
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['pmid'])
        for pmid in pmids:
            writer.writerow([pmid])
    
    print(f"\n✅ Generated simple format: {output_path}")
    print(f"   {len(pmids)} unique PMIDs")


def generate_detailed_format(studies: List[Dict], output_path: Path) -> None:
    """
    Generate enhanced CSV file with PMID, DOI, and metadata (Wave 2 format).
    
    Format:
        pmid,first_author,year,title,journal,doi
        12345678,Smith,2020,Title here,Journal Name,10.1234/example
        ...
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Deduplicate by PMID (keep first occurrence)
    seen_pmids = set()
    unique_studies = []
    for study in studies:
        pmid = study.get('pmid')
        if pmid and pmid not in seen_pmids:
            seen_pmids.add(pmid)
            unique_studies.append(study)
        elif not pmid:
            # Include studies without PMID (they might have DOI)
            unique_studies.append(study)
    
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['pmid', 'first_author', 'year', 'title', 'journal', 'doi'])
        
        for study in unique_studies:
            writer.writerow([
                study.get('pmid', ''),
                study.get('first_author', ''),
                study.get('year', ''),
                study.get('title', ''),
                study.get('journal', ''),
                study.get('doi', '')
            ])
    
    print(f"\n✅ Generated detailed format: {output_path}")
    print(f"   {len(unique_studies)} unique studies (with metadata)")


def generate_statistics_report(
    study_name: str,
    total_studies: int,
    accepted_studies: List[Dict],
    rejected_studies: List[Dict],
    min_confidence: float,
    output_path: Path
) -> None:
    """
    Generate statistics report about gold standard generation.
    """
    # Coverage metrics
    with_pmid = sum(1 for s in accepted_studies if s.get('pmid'))
    with_doi = sum(1 for s in accepted_studies if s.get('doi'))
    with_both = sum(1 for s in accepted_studies if s.get('pmid') and s.get('doi'))
    with_neither = sum(1 for s in accepted_studies if not s.get('pmid') and not s.get('doi'))
    
    # Confidence distribution
    confidences = []
    for study in accepted_studies:
        metadata = study.get('lookup_metadata', {})
        conf = metadata.get('confidence')
        if conf is not None:
            confidences.append(conf)
    
    # Source breakdown
    sources = Counter()
    for study in accepted_studies:
        metadata = study.get('lookup_metadata', {})
        source = metadata.get('source', 'Unknown')
        sources[source] += 1
    
    # Generate report
    report_lines = [
        f"# Gold Standard Generation Report",
        f"",
        f"**Study**: {study_name}",
        f"**Generated**: {Path.cwd().name}",
        f"**Confidence Threshold**: {min_confidence}",
        f"",
        f"## Summary Statistics",
        f"",
        f"- **Total Included Studies**: {total_studies}",
        f"- **Accepted** (confidence ≥ {min_confidence}): {len(accepted_studies)}",
        f"- **Rejected** (confidence < {min_confidence}): {len(rejected_studies)}",
        f"",
        f"## Coverage Metrics",
        f"",
        f"| Metric | Count | Percentage |",
        f"|--------|-------|------------|",
        f"| With PMID | {with_pmid} | {with_pmid/len(accepted_studies)*100:.1f}% |",
        f"| With DOI | {with_doi} | {with_doi/len(accepted_studies)*100:.1f}% |",
        f"| With Both | {with_both} | {with_both/len(accepted_studies)*100:.1f}% |",
        f"| With Neither | {with_neither} | {with_neither/len(accepted_studies)*100:.1f}% |",
        f"",
    ]
    
    # Add confidence distribution if available
    if confidences:
        avg_conf = sum(confidences) / len(confidences)
        min_conf = min(confidences)
        max_conf = max(confidences)
        
        report_lines.extend([
            f"## Confidence Distribution",
            f"",
            f"- **Average**: {avg_conf:.3f}",
            f"- **Range**: {min_conf:.3f} - {max_conf:.3f}",
            f"- **Studies with confidence**: {len(confidences)} / {len(accepted_studies)}",
            f"",
        ])
    
    # Add source breakdown
    if sources:
        report_lines.extend([
            f"## Lookup Sources",
            f"",
        ])
        for source, count in sources.most_common():
            pct = count / len(accepted_studies) * 100
            report_lines.append(f"- **{source}**: {count} ({pct:.1f}%)")
        report_lines.append("")
    
    # Warnings
    warnings = []
    
    pmid_coverage = with_pmid / len(accepted_studies) * 100
    if pmid_coverage < 70:
        warnings.append(f"⚠️  Low PMID coverage ({pmid_coverage:.1f}%)")
        warnings.append(f"   Expected: >70% for biomedical systematic reviews")
        warnings.append(f"   Suggestion: Check extraction and PubMed lookup logs")
    
    if with_neither > 0:
        warnings.append(f"⚠️  {with_neither} studies have neither PMID nor DOI")
        warnings.append(f"   These studies cannot be matched in evaluation")
        warnings.append(f"   Suggestion: Manual review recommended")
    
    if len(rejected_studies) > len(accepted_studies) * 0.2:
        pct_rejected = len(rejected_studies) / total_studies * 100
        warnings.append(f"⚠️  High rejection rate ({pct_rejected:.1f}%)")
        warnings.append(f"   {len(rejected_studies)} studies rejected due to low confidence")
        warnings.append(f"   Suggestion: Review rejected studies or lower threshold")
    
    if warnings:
        report_lines.extend([
            f"## Warnings",
            f"",
        ])
        report_lines.extend(warnings)
        report_lines.append("")
    
    # Rejected studies details (if any)
    if rejected_studies:
        report_lines.extend([
            f"## Rejected Studies (Low Confidence)",
            f"",
        ])
        for study in rejected_studies:
            metadata = study.get('lookup_metadata', {})
            conf = metadata.get('confidence', 'N/A')
            title = study.get('title', 'Unknown')[:60]
            report_lines.append(f"- [{study.get('reference_number', '?')}] {title}... (conf: {conf})")
        report_lines.append("")
    
    # Write report
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))
    
    print(f"\n📊 Generated statistics report: {output_path}")
    
    # Print warnings to console
    if warnings:
        print(f"\n⚠️  WARNINGS:")
        for warning in warnings:
            print(f"   {warning}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate gold standard PMID/DOI files from included_studies.json",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage (generates both formats)
  python scripts/generate_gold_standard.py ai_2022
  
  # Higher confidence threshold
  python scripts/generate_gold_standard.py Godos_2024 --min-confidence 0.90
  
  # Generate only simple format
  python scripts/generate_gold_standard.py sleep_apnea --simple-only
  
  # Custom paths
  python scripts/generate_gold_standard.py ai_2022 \\
      --input studies/ai_2022/included_studies.json \\
      --output studies/ai_2022/gold_pmids_ai_2022.csv
        """
    )
    
    parser.add_argument(
        'study_name',
        help='Name of the study (e.g., ai_2022, Godos_2024)'
    )
    
    parser.add_argument(
        '--input',
        dest='input_path',
        help='Path to included_studies.json (default: studies/{study_name}/included_studies.json)'
    )
    
    parser.add_argument(
        '--output',
        dest='output_path',
        help='Path for simple format CSV (default: studies/{study_name}/gold_pmids_{study_name}.csv)'
    )
    
    parser.add_argument(
        '--min-confidence',
        type=float,
        default=0.85,
        help='Minimum confidence threshold for accepting studies (default: 0.85)'
    )
    
    parser.add_argument(
        '--simple-only',
        action='store_true',
        help='Generate only the simple PMID-only format (skip detailed format)'
    )
    
    parser.add_argument(
        '--no-report',
        action='store_true',
        help='Skip generating statistics report'
    )
    
    args = parser.parse_args()
    
    # Determine paths
    study_dir = Path('studies') / args.study_name
    
    input_path = Path(args.input_path) if args.input_path else study_dir / 'included_studies.json'
    output_simple = Path(args.output_path) if args.output_path else study_dir / f'gold_pmids_{args.study_name}.csv'
    output_detailed = study_dir / f'gold_pmids_{args.study_name}_detailed.csv'
    output_report = study_dir / f'gold_generation_report_{args.study_name}.md'
    
    # Validate confidence threshold
    if not (0.0 <= args.min_confidence <= 1.0):
        print(f"❌ Error: --min-confidence must be between 0.0 and 1.0")
        sys.exit(1)
    
    print(f"🔍 Loading included studies from: {input_path}")
    
    # Load data
    data = load_included_studies(input_path)
    study_name = data.get('study_name', args.study_name)
    total_studies = data.get('total_included_studies', 0)
    included_studies = data.get('included_studies', [])
    
    if not included_studies:
        print(f"❌ Error: No included studies found in {input_path}")
        sys.exit(1)
    
    print(f"✓ Loaded {len(included_studies)} included studies")
    
    # Filter by confidence
    print(f"\n🔍 Filtering by confidence threshold: {args.min_confidence}")
    accepted, rejected = filter_by_confidence(included_studies, args.min_confidence)
    
    print(f"✓ Accepted: {len(accepted)} studies")
    if rejected:
        print(f"⚠️  Rejected: {len(rejected)} studies (low confidence)")
    
    if not accepted:
        print(f"❌ Error: No studies meet the confidence threshold")
        print(f"   Try lowering --min-confidence or check lookup quality")
        sys.exit(1)
    
    # Extract PMIDs
    pmids = extract_pmids(accepted, deduplicate=True)
    
    if not pmids:
        print(f"❌ Error: No PMIDs found in accepted studies")
        print(f"   All studies might be missing PMIDs (check lookup logs)")
        sys.exit(1)
    
    # Generate simple format
    generate_simple_format(pmids, output_simple)
    
    # Generate detailed format (unless --simple-only)
    if not args.simple_only:
        generate_detailed_format(accepted, output_detailed)
    
    # Generate statistics report (unless --no-report)
    if not args.no_report:
        generate_statistics_report(
            study_name,
            total_studies,
            accepted,
            rejected,
            args.min_confidence,
            output_report
        )
    
    # Final summary
    print(f"\n{'='*60}")
    print(f"✅ Gold standard generation complete!")
    print(f"{'='*60}")
    print(f"Study: {study_name}")
    print(f"Total studies: {total_studies}")
    print(f"Accepted: {len(accepted)} ({len(accepted)/total_studies*100:.1f}%)")
    print(f"Unique PMIDs: {len(pmids)}")
    print(f"")
    print(f"Files generated:")
    print(f"  1. {output_simple}")
    if not args.simple_only:
        print(f"  2. {output_detailed}")
    if not args.no_report:
        print(f"  3. {output_report}")
    print(f"")
    print(f"Next steps:")
    print(f"  • Review the statistics report for quality checks")
    print(f"  • Use gold_pmids_{args.study_name}.csv in evaluation workflow")
    print(f"  • Compare with existing gold standard (if available)")
    print(f"")


if __name__ == "__main__":
    main()
